### ISSUE TITLE
No option to enable 2FA for SSO users 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#30]
## Describe the bug

As OTF staff, when I am logged into my account via SSO I am not prompted to add 2FA in order to authenticate my account. Furthermore, the account profile page does not include a direct path/link to enabling 2FA and instead when clicking on the absolute path, I am taken to an error page. 

## Expected behavior

SSO improves user experience but doesn't address the need for stronger authentication which is the expected behavior. 

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff

**Comment by Techslammer** [comment]
This is the page that I land on when i type the absolute path to the 2fa set-up page: ![Screenshot 2021-12-07 1 13 13 PM](https://user-images.githubusercontent.com/93009150/145085083-085f691e-71b1-4ef0-9e84-09acab5e5d54.png)

**Comment by Techslammer** [comment]
I would like 2FA to be required for all SSO users

**Comment by frjo** [comment]
When you log in via Google you already have 2FA on your Google account. Do OTF staff really want two layers of 2FA? What does that add to security?

**Comment by Techslammer** [comment]
That's a great second question. And the reason why i added the question label since I wasn't sure if this needed any dev time next year for this if the likelihood that someone could take over a staff member's account and bypass 2fa via the Google SSO is unlikely.  I'd rather focus non-dev time in encouraging non-otf staff users of OTF to enable 2fa and dev time to make it easy for them to do this.

**Comment by Techslammer** [comment]
I'd like to close this issue with the possibility to return to it in the future but feel good about @frjo reframing and logic
